### ISSUE TITLE
It should check if there's argument values before trying to split them.

### ISSUE THREAD

**Issue by alanrsoares** [substack/tzloc#2]
```
$ tzloc

/usr/local/lib/node_modules/tzloc/node_modules/parse-messy-time/index.js:21
    var tokens = str.split(tokre).filter(Boolean).map(lc);
                     ^
TypeError: Cannot call method 'split' of undefined
    at module.exports (/usr/local/lib/node_modules/tzloc/node_modules/parse-messy-time/index.js:21:22)
    at module.exports (/usr/local/lib/node_modules/tzloc/index.js:7:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/tzloc/bin/cmd.js:76:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
```

**Comment by hemanth** [comment]
Came to fix the same,  :+1:
